### PR TITLE
Cherry-pick needed commits from golden repo

### PR DESCRIPTION
**Pull request by hirenvadalia**
Cherry-pick below commits:
* https://github.com/openpbs/openpbs/commit/58a8c2d5a10dab066faa92a2694c53811080785d
* https://github.com/openpbs/openpbs/commit/3b1c17288aa65c56df36db13812b3804f790b0dc
* https://github.com/openpbs/openpbs/commit/4bbecab5de4b16458227aa120fcda6183ac6923b
* https://github.com/openpbs/openpbs/commit/cc7d9a233b58e260ac1cb1157bd68bcf9f19c324
* https://github.com/openpbs/openpbs/commit/66c4e331b96b0eaf0e97ef80a95b219f85142c86

### CODE REVIEW

**Comment by hirenvadalia** [comment]
Force pushed to get rid of two Travis check

**Comment by subhasisb** [comment]
It is impossible to review this, so any chance u can verify this some other way - like a TH3 run? If not, i will simply merge it and fix issues as we face them

**Comment by agrawalravi90** [comment]
ya, please do TH3, it should work now

**Comment by hirenvadalia** [comment]
Description: Tests from given sources on platforms CENTOS7, UBUNTU1804, SUSE15, UBUNTU1604
Platforms: CENTOS7,UBUNTU1804,SUSE15,UBUNTU1604
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|2469|3510|40|17|0|0|3453|

**Pull request merged**
